using System.Text;

namespace RobloxCSharp.RobloxApi.Generator
{

	public static class ClassEmitter
	{
		private const string RootSuperclass = "<<<ROOT>>>";

		public static string Emit(ApiClass cls, DocsSource docs)
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("using System;");
			sb.AppendLine();
			sb.AppendLine("namespace RobloxCSharp.RobloxApi");
			sb.AppendLine("{");

			string name = TypeMapper.SanitizeIdentifier(cls.Name);
			string inherits = cls.Superclass == RootSuperclass
				? ""
				: $" : {TypeMapper.SanitizeIdentifier(cls.Superclass)}";

			string? classSummary = XmlDocFormatter.FormatSummary(docs.ForClass(cls.Name), "\t");
			if (classSummary is not null) sb.Append(classSummary);
			sb.AppendLine($"\t[RobloxBuiltin]");
			sb.AppendLine($"\tpublic class {name}{inherits}");
			sb.AppendLine("\t{");

			HashSet<string> seenNames = new();
			int written = 0;

			foreach (ApiMember m in cls.Members)
			{
				if (ShouldSkip(m)) continue;

				string sanitized = TypeMapper.SanitizeIdentifier(m.Name);
				if (!seenNames.Add(sanitized)) continue;

				if (sanitized == name) continue;

				string? line = EmitMember(m);
				if (line is null) continue;

				if (written > 0) sb.AppendLine();
				string? memberSummary = XmlDocFormatter.FormatSummary(docs.ForClassMember(cls.Name, m.Name), "\t\t");
				if (memberSummary is not null) sb.Append(memberSummary);
				sb.Append(line);
				written++;
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}

		private static bool ShouldSkip(ApiMember m)
		{
			return m.HasTag("Deprecated") || m.HasTag("Hidden") || m.HasTag("NotBrowsable");
		}

		private static string? EmitMember(ApiMember m) => m.MemberType switch
		{
			"Property" => EmitProperty(m),
			"Function" => EmitFunction(m),
			"Event" => EmitEvent(m),
			"Callback" => EmitCallback(m),
			_ => null,
		};

		private static string EmitProperty(ApiMember m)
		{
			string type = TypeMapper.ToCSharp(m.ValueType);
			string name = TypeMapper.SanitizeIdentifier(m.Name);
			string accessors = m.HasTag("ReadOnly") ? "{ get; }" : "{ get; set; }";
			return $"\t\tpublic {type} {name} {accessors}\n";
		}

		private static string EmitFunction(ApiMember m)
		{
			string ret = ReturnTypeToCSharp(m.ReturnType);
			string name = TypeMapper.SanitizeIdentifier(m.Name);
			string parameters = EmitParameters(m);
			return $"\t\tpublic extern {ret} {name}({parameters});\n";
		}

		private static string ReturnTypeToCSharp(List<ApiTypeRef> returns)
		{
			if (returns.Count == 0) return "void";
			if (returns.Count == 1) return TypeMapper.ToCSharp(returns[0]);

			return "(" + string.Join(", ", returns.Select(TypeMapper.ToCSharp)) + ")";
		}

		private static string EmitEvent(ApiMember m)
		{
			string name = TypeMapper.SanitizeIdentifier(m.Name);
			string actionType = EventActionType(m);
			return $"\t\tpublic event {actionType} {name};\n";
		}

		private static string EmitCallback(ApiMember m)
		{

			string ret = ReturnTypeToCSharp(m.ReturnType);
			string name = TypeMapper.SanitizeIdentifier(m.Name);

			string delegateType;
			if (m.Parameters.Count == 0)
			{
				delegateType = ret == "void" ? "Action" : $"Func<{ret}>";
			}
			else
			{
				delegateType = ret == "void"
					? $"Action<{ParamTypes(m)}>"
					: $"Func<{ParamTypesWithReturn(m, ret)}>";
			}

			return $"\t\tpublic {delegateType} {name} {{ get; set; }}\n";
		}

		private static string EmitParameters(ApiMember m)
		{
			if (m.Parameters.Count == 0) return "";
			List<string> parts = new();
			HashSet<string> seenParamNames = new();
			foreach (ApiParam p in m.Parameters)
			{
				string type = TypeMapper.ToCSharp(p.Type);
				string pname = TypeMapper.SanitizeIdentifier(string.IsNullOrEmpty(p.Name) ? "arg" : p.Name);

				string original = pname;
				int counter = 1;
				while (!seenParamNames.Add(pname)) pname = $"{original}{counter++}";
				parts.Add($"{type} {pname}");
			}
			return string.Join(", ", parts);
		}

		private static string EventActionType(ApiMember m)
		{
			if (m.Parameters.Count == 0) return "Action";
			return $"Action<{ParamTypes(m)}>";
		}

		private static string ParamTypes(ApiMember m)
			=> string.Join(", ", m.Parameters.Select(p => TypeMapper.ToCSharp(p.Type)));

		private static string ParamTypesWithReturn(ApiMember m, string ret)
			=> string.Join(", ", m.Parameters.Select(p => TypeMapper.ToCSharp(p.Type)).Append(ret));
	}
}
