using System.Text;

namespace RobloxCSharp.RobloxApi.Generator
{
	// Emits a populated C# class body for a single DataType, from its creator-docs YAML schema.
	// Falls back to DataTypeEmitter.Emit (empty stub) if the schema isn't available.
	public static class DataTypeBodyEmitter
	{
		public static string Emit(DataTypeSchema schema, HashSet<string> knownEnumNames)
		{
			string className = TypeMapper.SanitizeIdentifier(schema.name);

			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("using System;");
			sb.AppendLine();
			sb.AppendLine("namespace RobloxCSharp.RobloxApi");
			sb.AppendLine("{");
			sb.AppendLine("\t[RobloxBuiltin]");
			sb.AppendLine($"\tpublic class {className}");
			sb.AppendLine("\t{");

			HashSet<string> seenSignatures = new();
			int written = 0;

			foreach (DtConstructor c in schema.constructors)
			{
				if (IsDeprecated(c.tags, c.deprecation_message)) continue;
				string? line = EmitConstructor(c, className, knownEnumNames, seenSignatures);
				if (line is null) continue;
				if (written > 0) sb.AppendLine();
				sb.Append(line);
				written++;
			}

			foreach (DtProperty p in schema.properties)
			{
				if (IsDeprecated(p.tags, p.deprecation_message)) continue;
				string? line = EmitProperty(p, className, knownEnumNames, seenSignatures);
				if (line is null) continue;
				if (written > 0) sb.AppendLine();
				sb.Append(line);
				written++;
			}

			foreach (DtMethod m in schema.methods)
			{
				if (IsDeprecated(m.tags, m.deprecation_message)) continue;
				string? line = EmitMethod(m, className, knownEnumNames, isStatic: false, seenSignatures);
				if (line is null) continue;
				if (written > 0) sb.AppendLine();
				sb.Append(line);
				written++;
			}

			foreach (DtMethod f in schema.functions)
			{
				if (IsDeprecated(f.tags, f.deprecation_message)) continue;
				string? line = EmitMethod(f, className, knownEnumNames, isStatic: true, seenSignatures);
				if (line is null) continue;
				if (written > 0) sb.AppendLine();
				sb.Append(line);
				written++;
			}

			foreach (DtMathOp op in schema.math_operations)
			{
				if (IsDeprecated(op.tags, op.deprecation_message)) continue;
				string? line = EmitMathOp(op, className, knownEnumNames, seenSignatures);
				if (line is null) continue;
				if (written > 0) sb.AppendLine();
				sb.Append(line);
				written++;
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}

		// ---- constructors ----

		// `Vector3.new(x, y, z)` → C# constructor `public Vector3(...)`
		// `Vector3.FromNormalId(n)` → C# static factory `public static Vector3 FromNormalId(...)`
		private static string? EmitConstructor(DtConstructor c, string className, HashSet<string> enums, HashSet<string> sigs)
		{
			string shortName = ShortName(c.name);
			string parameters = EmitParameters(c.parameters, enums);

			string signature;
			string body;
			if (string.Equals(shortName, "new", StringComparison.OrdinalIgnoreCase))
			{
				signature = $"public {className}({parameters})";
				body = "{ }";
			}
			else
			{
				signature = $"public static {className} {TypeMapper.SanitizeIdentifier(shortName)}({parameters})";
				body = "=> default;";
			}

			if (!sigs.Add(SigKey(signature))) return null;
			return $"\t\t{signature} {body}\n";
		}

		// ---- properties ----

		// Static vs instance heuristic: Roblox API convention for DataTypes uses
		// lowercase-first-letter names for statics (Vector3.zero, Vector3.xAxis)
		// and PascalCase for instance components (Vector3.X, Vector3.Magnitude).
		private static string? EmitProperty(DtProperty p, string className, HashSet<string> enums, HashSet<string> sigs)
		{
			string shortName = ShortName(p.name);
			string sanitized = TypeMapper.SanitizeIdentifier(shortName);
			if (sanitized == className) return null;

			string type = MapYamlType(p.type, enums);
			bool isStatic = IsLowercaseFirstLetter(shortName);

			string signature = isStatic
				? $"public static {type} {sanitized}"
				: $"public {type} {sanitized}";

			if (!sigs.Add(SigKey(signature))) return null;

			string body = isStatic ? "=> default;" : "{ get; }";
			return $"\t\t{signature} {body}\n";
		}

		// ---- methods / functions ----

		private static string? EmitMethod(DtMethod m, string className, HashSet<string> enums, bool isStatic, HashSet<string> sigs)
		{
			string shortName = ShortName(m.name);
			string sanitized = TypeMapper.SanitizeIdentifier(shortName);
			if (sanitized == className) return null;

			string ret = m.returns.Count == 0
				? "void"
				: m.returns.Count == 1
					? MapYamlType(m.returns[0].type, enums)
					: "(" + string.Join(", ", m.returns.Select(r => MapYamlType(r.type, enums))) + ")";

			string parameters = EmitParameters(m.parameters, enums);
			string staticKw = isStatic ? "static " : "";

			string signature = $"public {staticKw}extern {ret} {sanitized}({parameters})";
			if (!sigs.Add(SigKey(signature))) return null;
			return $"\t\t{signature};\n";
		}

		// ---- operators ----

		// Only emit operators C# accepts (at least one operand must be the declaring class).
		// Punt on a few Lua-only operators (e.g. `..`) that have no C# equivalent.
		private static string? EmitMathOp(DtMathOp op, string className, HashSet<string> enums, HashSet<string> sigs)
		{
			string? csOp = MapOperator(op.operation);
			if (csOp is null) return null;

			string a = MapYamlType(op.type_a, enums);
			string b = MapYamlType(op.type_b, enums);
			string ret = MapYamlType(op.return_type, enums);

			if (a != className && b != className) return null;

			string signature = $"public static {ret} operator {csOp}({a} a, {b} b)";
			if (!sigs.Add(SigKey(signature))) return null;
			return $"\t\t{signature} => default;\n";
		}

		private static string? MapOperator(string op) => op switch
		{
			"+" => "+",
			"-" => "-",
			"*" => "*",
			"/" => "/",
			"%" => "%",
			"//" => null, // Luau floor-div; no C# equivalent
			"^" => null,  // Luau pow; not an arithmetic operator in C#
			".." => null, // string concat; no operator overload in C#
			"==" => "==",
			"<" => "<",
			">" => ">",
			"<=" => "<=",
			">=" => ">=",
			_ => null,
		};

		// ---- shared helpers ----

		private static string EmitParameters(List<DtParam> parameters, HashSet<string> enums)
		{
			if (parameters.Count == 0) return "";

			// C# requires all optional params after all required ones. Find the
			// last index that *must* be required; everything before becomes required too.
			int lastRequiredIndex = -1;
			for (int i = 0; i < parameters.Count; i++)
			{
				if (MapDefaultValue(parameters[i].@default, "") is null)
					lastRequiredIndex = i;
			}

			List<string> parts = new();
			HashSet<string> seen = new();
			for (int i = 0; i < parameters.Count; i++)
			{
				DtParam p = parameters[i];
				string type = MapYamlType(p.type, enums);
				string name = TypeMapper.SanitizeIdentifier(string.IsNullOrEmpty(p.name) ? "arg" : p.name);
				string original = name;
				int counter = 1;
				while (!seen.Add(name)) name = $"{original}{counter++}";

				string? defaultVal = i > lastRequiredIndex ? MapDefaultValue(p.@default, type) : null;
				parts.Add(defaultVal is null ? $"{type} {name}" : $"{type} {name} = {defaultVal}");
			}
			return string.Join(", ", parts);
		}

		private static string? MapDefaultValue(string? raw, string csharpType)
		{
			if (raw is null) return null;
			raw = raw.Trim();
			if (raw.Length == 0) return null;

			// Numeric literals
			if (double.TryParse(raw, System.Globalization.NumberStyles.Any,
				System.Globalization.CultureInfo.InvariantCulture, out _))
			{
				return raw;
			}

			// Bool literals
			if (raw == "true" || raw == "false") return raw;

			// nil → default (works for any C# type)
			if (raw == "nil") return "default";

			// Anything else — strings with special chars, enum values, etc. — skip
			// to keep the signature compilable rather than guess wrong.
			return null;
		}

		private static string MapYamlType(string yamlType, HashSet<string> knownEnumNames)
		{
			if (string.IsNullOrEmpty(yamlType)) return "object";

			string clean = yamlType.Trim().TrimEnd('?');

			// Lua empty-tuple notation for "no return values"
			if (clean == "()" || clean == "( )") return "void";

			// Union types: `string | number`, `Instance | nil`. Punt to object — C# unions need OneOf-style libs.
			if (clean.Contains('|')) return "object";

			// Generic wrappers (angle bracket form): Array<Vector3>, Tuple<CFrame>, etc.
			int lt = clean.IndexOf('<');
			if (lt > 0 && clean.EndsWith(">"))
			{
				string wrapper = clean[..lt];
				string inner = clean.Substring(lt + 1, clean.Length - lt - 2).Trim().TrimEnd('?');
				return MapWrappedType(wrapper, inner, knownEnumNames);
			}

			// Dot-notation wrappers: Enum.Material, Class.Instance, etc.
			int dot = clean.IndexOf('.');
			if (dot > 0)
			{
				string wrapper = clean[..dot];
				string inner = clean[(dot + 1)..].Trim().TrimEnd('?');
				return MapWrappedType(wrapper, inner, knownEnumNames);
			}

			return MapSimpleType(clean, knownEnumNames);
		}

		private static string MapSimpleType(string clean, HashSet<string> knownEnumNames) => clean switch
		{
			"number" => "double",
			"int" => "int",
			"int64" => "long",
			"float" => "float",
			"double" => "double",
			"bool" or "boolean" or "Boolean" => "bool",
			"string" or "String" => "string",
			"void" => "void",
			"nil" or "null" or "_" or "" => "object",
			"Variant" or "any" or "Any" => "object",
			"Tuple" => "object",
			"Function" or "function" => "Delegate",
			"Dictionary" or "Map" or "Table" or "table" => "object",
			"Array" => "object",
			"Object" => "Object", // The Roblox Object class (Instance root), not System.Object
			"Opaque" => "object", // Internal marker type
			_ => knownEnumNames.Contains(clean)
				? $"Enums.{TypeMapper.SanitizeIdentifier(clean)}"
				: TypeMapper.SanitizeIdentifier(clean),
		};

		private static string MapWrappedType(string wrapper, string inner, HashSet<string> enums)
		{
			string innerMapped = MapSimpleType(inner, enums);
			return wrapper switch
			{
				"Enum" => $"Enums.{TypeMapper.SanitizeIdentifier(inner)}",
				"Class" => TypeMapper.SanitizeIdentifier(inner),
				"Array" => $"{innerMapped}[]",
				"Tuple" => innerMapped, // C# already represents multi-return as ValueTuple; single-wrapped tuple → just the inner type
				"Dictionary" or "Map" or "Table" => "object",
				"Optional" => innerMapped,
				"Variant" => "object",
				"Function" => "Delegate",
				_ => "object",
			};
		}

		// "Vector3.new" / "Vector3:Abs" / "Vector3.FromNormalId" → "new" / "Abs" / "FromNormalId"
		private static string ShortName(string fullName)
		{
			int dot = fullName.LastIndexOfAny(new[] { '.', ':' });
			return dot < 0 ? fullName : fullName[(dot + 1)..];
		}

		private static bool IsLowercaseFirstLetter(string s)
			=> s.Length > 0 && char.IsLower(s[0]);

		private static bool IsDeprecated(List<string> tags, string deprecationMessage)
			=> tags.Contains("Deprecated") || !string.IsNullOrEmpty(deprecationMessage);

		// Strip whitespace differences so the dedup catches semantic duplicates.
		private static string SigKey(string sig) => string.Concat(sig.Where(c => !char.IsWhiteSpace(c)));
	}
}
