using System.Text;

namespace RobloxCSharp.RobloxApi.Generator
{

	public static class DataTypeEmitter
	{
		public static string Emit(string typeName, DocsSource docs)
		{
			string name = TypeMapper.SanitizeIdentifier(typeName);
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("namespace RobloxCSharp.RobloxApi");
			sb.AppendLine("{");
			string? summary = XmlDocFormatter.FormatSummary(docs.ForDataType(typeName), "\t");
			if (summary is not null) sb.Append(summary);
			sb.AppendLine("\t[RobloxBuiltin]");
			sb.AppendLine($"\tpublic class {name}");
			sb.AppendLine("\t{");
			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}

		public static IEnumerable<string> Collect(ApiDump dump)
		{
			HashSet<string> seen = new();
			foreach (ApiClass cls in dump.Classes)
			{
				foreach (ApiMember m in cls.Members)
				{
					CollectFrom(m.ValueType, seen);
					foreach (ApiTypeRef r in m.ReturnType) CollectFrom(r, seen);
					foreach (ApiParam p in m.Parameters) CollectFrom(p.Type, seen);
				}
			}
			return seen;
		}

		private static void CollectFrom(ApiTypeRef? type, HashSet<string> sink)
		{
			if (type is null) return;
			if (type.Category != "DataType" || string.IsNullOrEmpty(type.Name)) return;

			string clean = type.Name.TrimEnd('?');
			if (clean.Length > 0) sink.Add(clean);
		}
	}
}
