using System.Text;

namespace RobloxCSharp.RobloxApi.Generator
{
	// Emits *empty* stub classes for every Roblox DataType (Vector3, CFrame, UDim, etc.)
	// referenced by any class member. First-cut output: enough for the project to compile,
	// no constructors/methods/properties yet — those come from a separate DataType schema.
	public static class DataTypeEmitter
	{
		public static string Emit(string typeName)
		{
			string name = TypeMapper.SanitizeIdentifier(typeName);
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("namespace RobloxCSharp.RobloxApi");
			sb.AppendLine("{");
			sb.AppendLine("\t[RobloxBuiltin]");
			sb.AppendLine($"\tpublic class {name}");
			sb.AppendLine("\t{");
			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}

		// Walks every member of every class and yields all distinct DataType names referenced.
		public static IEnumerable<string> Collect(ApiDump dump)
		{
			HashSet<string> seen = new();
			foreach (ApiClass cls in dump.Classes)
			{
				foreach (ApiMember m in cls.Members)
				{
					CollectFrom(m.ValueType, seen);
					foreach (ApiTypeRef r in m.ReturnType) CollectFrom(r, seen);
					foreach (ApiParam p in m.Parameters) CollectFrom(p.Type, seen);
				}
			}
			return seen;
		}

		private static void CollectFrom(ApiTypeRef? type, HashSet<string> sink)
		{
			if (type is null) return;
			if (type.Category != "DataType" || string.IsNullOrEmpty(type.Name)) return;

			// Strip nullable suffix some return types carry (e.g. "Vector3?")
			string clean = type.Name.TrimEnd('?');
			if (clean.Length > 0) sink.Add(clean);
		}
	}
}
