using System.Text;

namespace RobloxCSharp.RobloxApi.Generator
{
	// Emits a C# enum per Roblox enum, in the RobloxCSharp.RobloxApi.Enums sub-namespace
	// (so user code can reference `Enums.NormalId.Top` from inside RobloxCSharp.RobloxApi).
	public static class EnumEmitter
	{
		public static string Emit(ApiEnum e)
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("namespace RobloxCSharp.RobloxApi.Enums");
			sb.AppendLine("{");
			sb.AppendLine($"\tpublic enum {TypeMapper.SanitizeIdentifier(e.Name)}");
			sb.AppendLine("\t{");

			HashSet<string> seenNames = new();
			HashSet<int> seenValues = new();
			foreach (ApiEnumItem item in e.Items)
			{
				string name = TypeMapper.SanitizeIdentifier(item.Name);
				if (!seenNames.Add(name)) continue;
				// Duplicate values within an enum are legal in C# but noisy. Skip.
				if (!seenValues.Add(item.Value)) continue;
				sb.AppendLine($"\t\t{name} = {item.Value},");
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
