using System.Text;

namespace RobloxCSharp.RobloxApi.Generator
{

	public static class EnumEmitter
	{
		public static string Emit(ApiEnum e, DocsSource docs)
		{
			StringBuilder sb = new();
			sb.AppendLine("// <auto-generated/>");
			sb.AppendLine("namespace RobloxCSharp.RobloxApi.Enums");
			sb.AppendLine("{");
			sb.AppendLine($"\tpublic enum {TypeMapper.SanitizeIdentifier(e.Name)}");
			sb.AppendLine("\t{");

			HashSet<string> seenNames = new();
			HashSet<int> seenValues = new();
			bool firstWritten = false;
			foreach (ApiEnumItem item in e.Items)
			{
				string name = TypeMapper.SanitizeIdentifier(item.Name);
				if (!seenNames.Add(name)) continue;

				if (!seenValues.Add(item.Value)) continue;

				string? itemSummary = XmlDocFormatter.FormatSummary(docs.ForEnumItem(e.Name, item.Name), "\t\t");
				if (firstWritten && itemSummary is not null) sb.AppendLine();
				if (itemSummary is not null) sb.Append(itemSummary);
				sb.AppendLine($"\t\t{name} = {item.Value},");
				firstWritten = true;
			}

			sb.AppendLine("\t}");
			sb.AppendLine("}");
			return sb.ToString();
		}
	}
}
